"""Add TMS tables and columns

Revision ID: 1956a7403f9f
Revises: 24482872464d
Create Date: 2026-08-07 12:06:42.999785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1956a7403f9f'
down_revision: Union[str, None] = '24482872464d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_feedback',
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_feedback_language_code'), 'translation_feedback', ['language_code'], unique=False)
    op.create_index(op.f('ix_translation_feedback_scheme_id'), 'translation_feedback', ['scheme_id'], unique=False)
    op.create_table('translation_history',
    sa.Column('translation_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('translated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['translation_id'], ['scheme_translations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trans_hist_translation_id_version', 'translation_history', ['translation_id', 'version'], unique=True)
    op.create_index(op.f('ix_translation_history_translation_id'), 'translation_history', ['translation_id'], unique=False)
    op.add_column('scheme_translations', sa.Column('review_status', sa.Enum('pending', 'translated', 'outdated', 'failed', 'pending_review', 'approved', 'published', 'rejected', name='translation_status_enum'), nullable=True))
    op.add_column('scheme_translations', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('scheme_translations', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheme_translations', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheme_translations', sa.Column('review_comment', sa.String(), nullable=True))
    op.add_column('scheme_translations', sa.Column('last_editor', sa.UUID(), nullable=True))
    op.add_column('scheme_translations', sa.Column('last_reviewer', sa.UUID(), nullable=True))
    op.add_column('scheme_translations', sa.Column('manual_override', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('scheme_translations', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('scheme_translations', sa.Column('approved_version', sa.Integer(), nullable=True))
    op.alter_column('scheme_translations', 'status',
               existing_type=postgresql.ENUM('pending', 'translated', 'outdated', 'failed', 'pending_review', 'approved', 'published', 'rejected', name='translation_status_enum'),
               server_default='pending_review',
               existing_nullable=False)
    op.create_index(op.f('ix_scheme_translations_is_published'), 'scheme_translations', ['is_published'], unique=False)
    op.create_foreign_key(None, 'scheme_translations', 'users', ['last_editor'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'scheme_translations', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'scheme_translations', 'users', ['last_reviewer'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheme_translations', type_='foreignkey')
    op.drop_constraint(None, 'scheme_translations', type_='foreignkey')
    op.drop_constraint(None, 'scheme_translations', type_='foreignkey')
    op.drop_index(op.f('ix_scheme_translations_is_published'), table_name='scheme_translations')
    op.alter_column('scheme_translations', 'status',
               existing_type=postgresql.ENUM('pending', 'translated', 'outdated', 'failed', 'pending_review', 'approved', 'published', 'rejected', name='translation_status_enum'),
               server_default=sa.text("'translated'::translation_status_enum"),
               existing_nullable=False)
    op.drop_column('scheme_translations', 'approved_version')
    op.drop_column('scheme_translations', 'is_published')
    op.drop_column('scheme_translations', 'manual_override')
    op.drop_column('scheme_translations', 'last_reviewer')
    op.drop_column('scheme_translations', 'last_editor')
    op.drop_column('scheme_translations', 'review_comment')
    op.drop_column('scheme_translations', 'published_at')
    op.drop_column('scheme_translations', 'reviewed_at')
    op.drop_column('scheme_translations', 'approved_by')
    op.drop_column('scheme_translations', 'review_status')
    op.drop_index(op.f('ix_translation_history_translation_id'), table_name='translation_history')
    op.drop_index('ix_trans_hist_translation_id_version', table_name='translation_history')
    op.drop_table('translation_history')
    op.drop_index(op.f('ix_translation_feedback_scheme_id'), table_name='translation_feedback')
    op.drop_index(op.f('ix_translation_feedback_language_code'), table_name='translation_feedback')
    op.drop_table('translation_feedback')
    # ### end Alembic commands ###
