"""Add translation models

Revision ID: 797fd7422c34
Revises: 0004
Create Date: 2026-08-07 09:43:37.378558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '797fd7422c34'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_jobs',
    sa.Column('job_type', sa.String(), nullable=False, comment="Type of job, e.g., 'pilot_translation', 'full_translation'"),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', 'retry', 'paused', name='translation_job_status_enum'), server_default='pending', nullable=False),
    sa.Column('total_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_records', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_batch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_remaining', sa.Integer(), nullable=True, comment='Estimated time remaining in seconds'),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True, comment='Array of log events'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_translations',
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('translated_content', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('translation_quality', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'translated', 'outdated', 'failed', name='translation_status_enum'), server_default='translated', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'language_code', name='uq_translation_scheme_lang')
    )
    op.create_index(op.f('ix_scheme_translations_checksum'), 'scheme_translations', ['checksum'], unique=False)
    op.create_index(op.f('ix_scheme_translations_language_code'), 'scheme_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_scheme_translations_scheme_id'), 'scheme_translations', ['scheme_id'], unique=False)
    op.alter_column('chat_history', 'question',
               existing_type=sa.TEXT(),
               comment="The user's input message",
               existing_nullable=False)
    op.alter_column('chat_history', 'answer',
               existing_type=sa.TEXT(),
               comment='The AI-generated response',
               existing_nullable=False)
    op.alter_column('eligibility_rules', 'minimum_income',
               existing_type=sa.INTEGER(),
               comment='Minimum annual income in INR (NULL = no floor)',
               existing_comment='Minimum annual income in INR',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'maximum_income',
               existing_type=sa.INTEGER(),
               comment='Maximum annual income in INR (NULL = no ceiling)',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'education',
               existing_type=postgresql.ENUM('no_formal_education', 'primary', 'middle', 'secondary', 'higher_secondary', 'graduate', 'post_graduate', 'doctorate', 'other', name='education_enum'),
               comment='Minimum required education level',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'require_farmer',
               existing_type=sa.BOOLEAN(),
               comment='True = must be farmer; False = must NOT be farmer; None = irrelevant',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'require_disabled',
               existing_type=sa.BOOLEAN(),
               comment='True = must be disabled; None = irrelevant',
               existing_nullable=True)
    op.alter_column('profiles', 'annual_income',
               existing_type=sa.INTEGER(),
               comment='Annual household income in INR',
               existing_nullable=True)
    op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_profiles_category'), 'profiles', ['category'], unique=False)
    op.create_index(op.f('ix_profiles_state'), 'profiles', ['state'], unique=False)
    op.alter_column('schemes', 'scheme_code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique short code, e.g. PM-KISAN-2024',
               existing_nullable=False)
    op.alter_column('schemes', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='One-line summary shown in list views',
               existing_nullable=True)
    op.alter_column('schemes', 'full_description',
               existing_type=sa.TEXT(),
               comment='Detailed scheme description (was: description)',
               existing_nullable=True)
    op.alter_column('schemes', 'benefits',
               existing_type=sa.TEXT(),
               comment='What the beneficiary receives — cash, subsidy, asset, service',
               existing_nullable=True)
    op.alter_column('schemes', 'ministry',
               existing_type=sa.VARCHAR(length=300),
               comment='Administering ministry, e.g. Ministry of Agriculture',
               existing_nullable=True)
    op.alter_column('schemes', 'department',
               existing_type=sa.VARCHAR(length=300),
               comment='Administering department under the ministry',
               existing_nullable=True)
    op.alter_column('schemes', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment='NULL = central scheme applicable nationwide',
               existing_nullable=True)
    op.alter_column('schemes', 'district',
               existing_type=sa.VARCHAR(length=100),
               comment='Further geographic restriction to a district (rare)',
               existing_nullable=True)
    op.alter_column('schemes', 'application_start_date',
               existing_type=sa.DATE(),
               comment='Date from which applications are accepted',
               existing_nullable=True)
    op.alter_column('schemes', 'application_end_date',
               existing_type=sa.DATE(),
               comment='Last date for applications (NULL = always open)',
               existing_nullable=True)
    op.alter_column('schemes', 'official_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('schemes', 'official_pdf_url',
               existing_type=sa.VARCHAR(length=2000),
               comment='URL to official scheme guidelines PDF',
               existing_nullable=True)
    op.alter_column('schemes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='False = soft-deleted, hidden from public API',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schemes', 'is_featured',
               existing_type=sa.BOOLEAN(),
               comment='Highlighted on homepage / discovery page',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('schemes', 'view_count',
               existing_type=sa.INTEGER(),
               comment='Incremented on each public GET /schemes/{id} call',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('schemes', 'created_by',
               existing_type=sa.UUID(),
               comment='User UUID who created this record',
               existing_nullable=True)
    op.alter_column('schemes', 'updated_by',
               existing_type=sa.UUID(),
               comment='User UUID who last updated this record',
               existing_nullable=True)
    op.drop_constraint('uq_schemes_scheme_code', 'schemes', type_='unique')
    op.create_index(op.f('ix_schemes_is_featured'), 'schemes', ['is_featured'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_type'), 'schemes', ['scheme_type'], unique=False)
    op.drop_index('ix_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_schemes_scheme_type'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_is_featured'), table_name='schemes')
    op.create_unique_constraint('uq_schemes_scheme_code', 'schemes', ['scheme_code'])
    op.alter_column('schemes', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User UUID who last updated this record',
               existing_nullable=True)
    op.alter_column('schemes', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User UUID who created this record',
               existing_nullable=True)
    op.alter_column('schemes', 'view_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Incremented on each public GET /schemes/{id} call',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('schemes', 'is_featured',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Highlighted on homepage / discovery page',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('schemes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='False = soft-deleted, hidden from public API',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schemes', 'official_pdf_url',
               existing_type=sa.VARCHAR(length=2000),
               comment=None,
               existing_comment='URL to official scheme guidelines PDF',
               existing_nullable=True)
    op.alter_column('schemes', 'official_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('schemes', 'application_end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Last date for applications (NULL = always open)',
               existing_nullable=True)
    op.alter_column('schemes', 'application_start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date from which applications are accepted',
               existing_nullable=True)
    op.alter_column('schemes', 'district',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Further geographic restriction to a district (rare)',
               existing_nullable=True)
    op.alter_column('schemes', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='NULL = central scheme applicable nationwide',
               existing_nullable=True)
    op.alter_column('schemes', 'department',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Administering department under the ministry',
               existing_nullable=True)
    op.alter_column('schemes', 'ministry',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Administering ministry, e.g. Ministry of Agriculture',
               existing_nullable=True)
    op.alter_column('schemes', 'benefits',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='What the beneficiary receives — cash, subsidy, asset, service',
               existing_nullable=True)
    op.alter_column('schemes', 'full_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed scheme description (was: description)',
               existing_nullable=True)
    op.alter_column('schemes', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='One-line summary shown in list views',
               existing_nullable=True)
    op.alter_column('schemes', 'scheme_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique short code, e.g. PM-KISAN-2024',
               existing_nullable=False)
    op.drop_index(op.f('ix_profiles_state'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_category'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_unique_constraint('profiles_user_id_key', 'profiles', ['user_id'])
    op.alter_column('profiles', 'annual_income',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Annual household income in INR',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'require_disabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = must be disabled; None = irrelevant',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'require_farmer',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = must be farmer; False = must NOT be farmer; None = irrelevant',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'education',
               existing_type=postgresql.ENUM('no_formal_education', 'primary', 'middle', 'secondary', 'higher_secondary', 'graduate', 'post_graduate', 'doctorate', 'other', name='education_enum'),
               comment=None,
               existing_comment='Minimum required education level',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'maximum_income',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum annual income in INR (NULL = no ceiling)',
               existing_nullable=True)
    op.alter_column('eligibility_rules', 'minimum_income',
               existing_type=sa.INTEGER(),
               comment='Minimum annual income in INR',
               existing_comment='Minimum annual income in INR (NULL = no floor)',
               existing_nullable=True)
    op.alter_column('chat_history', 'answer',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='The AI-generated response',
               existing_nullable=False)
    op.alter_column('chat_history', 'question',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="The user's input message",
               existing_nullable=False)
    op.drop_index(op.f('ix_scheme_translations_scheme_id'), table_name='scheme_translations')
    op.drop_index(op.f('ix_scheme_translations_language_code'), table_name='scheme_translations')
    op.drop_index(op.f('ix_scheme_translations_checksum'), table_name='scheme_translations')
    op.drop_table('scheme_translations')
    op.drop_table('translation_jobs')
    # ### end Alembic commands ###
